version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  commands:
    - pip install nox
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - BASE_URL="/$READTHEDOCS_VERSION" nox -s docs
    - cp -a docs/_build/html/. "$READTHEDOCS_OUTPUT/html" && rm -r docs/_build
