version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  commands:
    - npm install -g mystmd
    - pip install .[docs]
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cd docs/ && BASE_URL="/$READTHEDOCS_VERSION" myst build --html --execute
    - cp -a docs/_build/html/. "$READTHEDOCS_OUTPUT/html" && rm -r docs/_build
