version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  commands:
    - pip install nox requests
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - BASE_URL="/docs/$READTHEDOCS_VERSION" nox -s docs
    # We must put this in a `/html/docs/` subfolder so jupyterbook.org has the right BASE_URL
    - mkdir "$READTHEDOCS_OUTPUT/html/docs"
    - cp -a docs/_build/html/. "$READTHEDOCS_OUTPUT/html/docs" && rm -r docs/_build
    # Create a root index.html that redirects to /docs/
    # We're doing it in Python to avoid any shell quoting issues
    - python -c "import os; open(os.environ['READTHEDOCS_OUTPUT']+'/html/index.html', 'w').write('<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\"0; url=docs/'+os.environ['READTHEDOCS_VERSION']+'/\"></head></html>')"
