name: 🐛 Bug Report
title: "[Bug]: "
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening up a bug report! To make sure that your report provides actionable information, please fill out the following fields:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened, and what did you expect to happen?
      placeholder: |
        When running command X, I expected Y to happen, but instead Z happened.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of Jupyter Book are you running?
      description: |
        Run `jupyter book -v` and report the result
      placeholder: v2.0.0a0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What Operating System are you using?
      multiple: true
      options:
        - Linux
        - Mac OS
        - Windows
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
 
