contact_links:
  - name: ❓ Ask a question
    url: https://github.com/orgs/jupyter-book/discussions/categories/q-a
    about: Questions about Jupyter Book or MyST are in our community forum.
  - name: 💡 Request an enhancement
    url: https://github.com/orgs/jupyter-book/discussions/categories/ideas
    about: Ideas for new functionality and improvements to Jupyter Book and MyST are in our community forum.
blank_issues_enabled: true
