name: Jupyter Book 2 Pre-Release Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to try out Jupyter Book 2 (pre-release).
        We expect there to be bugs and breakages, and this issue template should help us to track them down. Please fill in the following form:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        What version of Jupyter Book are you running?  
        Please run `jupyter book -v` and report the result
      placeholder: v2.0.0a0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What Operating System are you using?
      multiple: true
      options:
        - Linux
        - Mac OS
        - Windows
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
 
